sudo: required

services:
 - docker

before_install:
 - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run react-test npm test -- --coverage

after_success:
 - docker build -t ketankishore27/multi-client ./client
 - docker build -t ketankishore27/multi-nginx ./nginx
 - docker build -t ketankishore27/multi-server ./server
 - docker build -t ketankishore27/multi-worker ./worker

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 - docker push ketankishore27/multi-client
 - docker push ketankishore27/multi-nginx
 - docker push ketankishore27/multi-server
 - docker push ketankishore27/multi-worker
