sudo: required

services:
 - docker

before_install:
 - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run react-test npm test -- --coverage

after_success:
 - docker build -t ketankishore27/multi-client ./client
 - docker build -t ketankishore27/multi-nginx ./nginx
 - docker build -t ketankishore27/multi-server ./server
 - docker build -t ketankishore27/multi-worker ./worker

 - docker login -u "$DOCKER_ID" -p"$DOCKER_PASSWORD"

 - docker push ketankishore27/multi-client
 - docker push ketankishore27/multi-nginx
 - docker push ketankishore27/multi-server
 - docker push ketankishore27/multi-worker

deploy:
 provider: elasticbeanstalk
 region: us-east-1
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-us-east-1-878534241804
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
